```bash
uv venv .venv_wsl
source .venv_wsl/bin/activate
uv pip install -r OneDriveExplorer/requirements_wsl.txt 
```

In [1]:
import pandas as pd
import numpy as np
import pickle

In [3]:
folder1 = 'tmp/ztsdaf1471/sweeni/241231_0107ct/'
folder2 = 'tmp/ztsdaf1471/sweeni/250101_0257ct/'

In [5]:
fields = ['Type', 'fileStatus', 'diskLastAccessTime', 'diskCreationTime', 'lastChange', 'size', 'folderStatus', 'Path', 'Name', 'fileName', 'lastWriteCount']

In [11]:

df1 = pd.read_csv(folder1 + '/SQLite_DB_OneDrive.csv', skipinitialspace=True, usecols=fields,
                 converters={'diskLastAccessTime': pd.to_datetime,
                             'diskCreationTime': pd.to_datetime,
                             'lastChange': pd.to_datetime
                             }, 
                 dtype={'Type' : 'category',
                        'fileStatus' : 'category',
                        'folderStatus' : 'category'}
                        )
with open(folder1 + 'out.pickle','wb') as f:
    pickle.dump(df1,f)

In [7]:
df2 = pd.read_csv(folder2 + '/SQLite_DB_OneDrive.csv', skipinitialspace=True, usecols=fields,
                 converters={'diskLastAccessTime': pd.to_datetime,
                             'diskCreationTime': pd.to_datetime,
                             'lastChange': pd.to_datetime
                             }, 
                 dtype={'Type' : 'category',
                        'fileStatus' : 'category',
                        'folderStatus' : 'category'}
                        )
with open(folder2 + 'out.pickle','wb') as f:
    pickle.dump(df2,f)

In [8]:
with open(folder1 + 'out.pickle','rb') as f:
    df1=pickle.load(f)
with open(folder2 + 'out.pickle','rb') as f:
    df2=pickle.load(f)

In [9]:

# Id rows where Name is NaN
display(df1[(df1['Name'].isnull())])
# Delete the Scope entry row
df1.drop(df1[df1['Type'] == 'Scope'].index, inplace=True)
display(df1[(df1['Name'].isnull())])

,Type,Name,fileStatus,diskLastAccessTime,diskCreationTime,lastChange,size,folderStatus,Path,fileName,lastWriteCount
87770,Scope,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN

Empty DataFrame
Columns: [Type, Name, fileStatus, diskLastAccessTime, diskCreationTime, lastChange, size, folderStatus, Path, fileName, lastWriteCount]
Index: []

In [10]:
display(df2[(df2['Name'].isnull()) ].head())
df2.drop(df2[df2['Type'] == 'Scope'].index, inplace=True)
display(df2[(df2['Name'].isnull()) ].head())

,Type,Name,fileStatus,diskLastAccessTime,diskCreationTime,lastChange,size,folderStatus,Path,fileName,lastWriteCount
88366,Scope,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN
88367,Scope,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN

Empty DataFrame
Columns: [Type, Name, fileStatus, diskLastAccessTime, diskCreationTime, lastChange, size, folderStatus, Path, fileName, lastWriteCount]
Index: []

In [11]:
display(df1[(df1['Path'].isnull()) ])
display(df2[(df2['Path'].isnull()) ])

Empty DataFrame
Columns: [Type, Name, fileStatus, diskLastAccessTime, diskCreationTime, lastChange, size, folderStatus, Path, fileName, lastWriteCount]
Index: []

Empty DataFrame
Columns: [Type, Name, fileStatus, diskLastAccessTime, diskCreationTime, lastChange, size, folderStatus, Path, fileName, lastWriteCount]
Index: []

In [12]:
df1['file'] = df1['Path'] + '\\' + df1['Name']
df1 = df1.drop(columns=['Path', 'Name'])
df2['file'] = df2['Path'] + '\\' + df2['Name']
df2= df2.drop(columns=['Path', 'Name'])

In [13]:

# Remove this prefix from Path 	df9e9e556244467b9dabdc62d965839f
df1 = df1.replace(to_replace={'file': r'\w+\\\\'}, value='', regex=True)
df2 = df2.replace(to_replace={'file': r'\w+\\\\'}, value='', regex=True)
df1.set_index('file', drop=True, inplace=True)
df2.set_index('file', drop=True, inplace=True)

In [14]:
print(df1.info())
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
Index: 87770 entries, ztsdaf1471\G\Seema\BackupPlus\Seema\Backup - April 2009\1Ingage_GA\Ingage\Customers\Island\Island Simplified Phase 1\08252008\Ingage_source\Riskclick.Insurance.UW.Web\BusinessProcess\NewBusiness\WC\Review\DataView\Review.aspx to _wip
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Type                87770 non-null  category
 1   fileStatus          82302 non-null  category
 2   diskLastAccessTime  82301 non-null  datetime64[ns]
 3   diskCreationTime    82301 non-null  datetime64[ns]
 4   lastChange          82302 non-null  datetime64[ns]
 5   size                82302 non-null  object
 6   folderStatus        5468 non-null   category
 7   fileName            82257 non-null  object
 8   lastWriteCount      82257 non-null  float64
dtypes: category(3), datetime64[ns](3), float64(1), object(2)
memory usage: 4.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
Index: 88366 entries, ztsdaf1471\G\Seema\BackupPlus\Seema\Backup - April 2009\1Ingage_GA\Ingage\Customers\Island\Island Simplified Phase 1\08252008\Ingage_source\Riskclick.Insurance.UW.Web\BusinessProcess\NewBusiness\WC\Review\DataView\Review.aspx to _wip
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Type                88366 non-null  category
 1   fileStatus          82888 non-null  category
 2   diskLastAccessTime  82887 non-null  datetime64[ns]
 3   diskCreationTime    82887 non-null  datetime64[ns]
 4   lastChange          82888 non-null  datetime64[ns]
 5   size                82888 non-null  object
 6   folderStatus        5478 non-null   category
 7   fileName            82866 non-null  object
 8   lastWriteCount      82866 non-null  float64
dtypes: category(3), datetime64[ns](3), float64(1), object(2)
memory usage: 5.0+ MB
None

In [15]:
duplicates = df2[df2.index.duplicated()].sort_index()
duplicates.sort_values(by='lastChange', ascending=True, inplace=True)
duplicates.head()

Empty DataFrame
Columns: [Type, fileStatus, diskLastAccessTime, diskCreationTime, lastChange, size, folderStatus, fileName, lastWriteCount]
Index: []

In [16]:
# Check for duplicates
duplicates = df1[df1.index.duplicated()]
display(duplicates.sort_index().head())

# print(duplicates['Type'].unique())

# Check for duplicates
duplicates = df2[df2.index.duplicated()]
display(duplicates.sort_index().head())

# print(duplicates['Type'].unique())

Empty DataFrame
Columns: [Type, fileStatus, diskLastAccessTime, diskCreationTime, lastChange, size, folderStatus, fileName, lastWriteCount]
Index: []

Empty DataFrame
Columns: [Type, fileStatus, diskLastAccessTime, diskCreationTime, lastChange, size, folderStatus, fileName, lastWriteCount]
Index: []

In [17]:
# # Drop rows with duplicate indices
# df.sort_values(by='A', ascending=False, inplace=True)
# df = df.drop_duplicates(subset=df.index, keep='last')

In [20]:
result = pd.merge(df1, df2, on='file', how='outer')
# result = result.drop(columns=['folderStatus_x', 'diskCreationTime_y','Type_y','size_y','folderStatus_y'])
result = result.drop(columns=['folderStatus_x', 'folderStatus_y'])
result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 88397 entries, Attachments to ztsdaf1471\G\_To Do\iphone-manual copy
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Type_x                87770 non-null  category
 1   fileStatus_x          82302 non-null  category
 2   diskLastAccessTime_x  82301 non-null  datetime64[ns]
 3   diskCreationTime_x    82301 non-null  datetime64[ns]
 4   lastChange_x          82302 non-null  datetime64[ns]
 5   size_x                82302 non-null  object
 6   fileName_x            82257 non-null  object
 7   lastWriteCount_x      82257 non-null  float64
 8   Type_y                88366 non-null  category
 9   fileStatus_y          82888 non-null  category
 10  diskLastAccessTime_y  82887 non-null  datetime64[ns]
 11  diskCreationTime_y    82887 non-null  datetime64[ns]
 12  lastChange_y          82888 non-null  datetime64[ns]
 13  size_y                82888 non-null  object
 14  fileName_y            82866 non-null  object
 15  lastWriteCount_y      82866 non-null  float64
dtypes: category(4), datetime64[ns](6), float64(2), object(4)
memory usage: 9.1+ MB

In [21]:
result = result[['Type_x', 'Type_y',  'fileStatus_x', 'fileStatus_y', 'diskLastAccessTime_x',  'diskLastAccessTime_y',
       'lastChange_x', 'lastChange_y','fileName_x', 'fileName_y', 'lastWriteCount_x', 
       'lastWriteCount_y', 'size_x', 'size_y', 'diskCreationTime_x', 'diskCreationTime_y']]
display(result.head())

,Type_x,Type_y,fileStatus_x,fileStatus_y,diskLastAccessTime_x,diskLastAccessTime_y,lastChange_x,lastChange_y,fileName_x,fileName_y,lastWriteCount_x,lastWriteCount_y,size_x,size_y,diskCreationTime_x,diskCreationTime_y
file,,,,,,,,,,,,,,,,
Attachments,Folder,Folder,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
Attachments\2023.tax2023_as_filed,File,File,2,2,2024-12-30 22:08:32,2024-12-30 22:08:32,2024-04-14 02:50:13,2024-04-14 02:50:13,2023.tax2023_as_filed,2023.tax2023_as_filed,3472.0,3472.0,"2,705 KB","2,705 KB",2024-12-30 22:08:32,2024-12-30 22:08:32
Attachments\2023_Filing-all.pdf,File,File,2,2,2024-12-30 22:08:32,2024-12-30 22:08:32,2024-04-14 02:50:14,2024-04-14 02:50:14,2023_Filing-all.pdf,2023_Filing-all.pdf,3474.0,3474.0,742 KB,742 KB,2024-12-30 22:08:32,2024-12-30 22:08:32
Attachments\CR-2_9-17-signed 1.pdf,File,File,2,2,2024-12-30 22:08:31,2024-12-30 22:08:31,2023-10-02 19:37:25,2023-10-02 19:37:25,CR-2_9-17-signed 1.pdf,CR-2_9-17-signed 1.pdf,3465.0,3465.0,785 KB,785 KB,2024-12-30 22:08:31,2024-12-30 22:08:31
Attachments\CR-2_9-17-signed.pdf,File,File,2,2,2024-12-30 22:08:31,2024-12-30 22:08:31,2023-10-02 19:03:06,2023-10-02 19:03:06,CR-2_9-17-signed.pdf,CR-2_9-17-signed.pdf,3463.0,3463.0,785 KB,785 KB,2024-12-30 22:08:31,2024-12-30 22:08:31

In [27]:
print(result['fileStatus_x'].value_counts().index)
print(result['fileStatus_y'].value_counts().index)

CategoricalIndex(['2', '3'], categories=['2', '3'], ordered=False, dtype='category', name='fileStatus_x')
CategoricalIndex(['2'], categories=['2'], ordered=False, dtype='category', name='fileStatus_y')

In [31]:
# Note that df2 has only one category '2' for fileStatus_y
# trying to compare between fileStatus_x and fileStatus_y will result in error
# TypeError: Categoricals can only be compared if 'categories' are the same

result['fileStatus_y'] = result['fileStatus_y'].cat.add_categories('3')
print(result['fileStatus_y'].cat.categories)
print(result['fileStatus_y'].value_counts().index)

Index(['2', '3'], dtype='object')
CategoricalIndex(['2', '3'], categories=['2', '3'], ordered=False, dtype='category', name='fileStatus_y')

In [ ]:
# File status 3 may be when file is pending synch, 2 may be synch completed
result1 = result.loc[(result['fileStatus_x'] != result['fileStatus_y']) ] 
result1.head()

,Type_x,Type_y,fileStatus_x,fileStatus_y,diskLastAccessTime_x,diskLastAccessTime_y,lastChange_x,lastChange_y,fileName_x,fileName_y,lastWriteCount_x,lastWriteCount_y,size_x,size_y,diskCreationTime_x,diskCreationTime_y
file,,,,,,,,,,,,,,,,
Attachments,Folder,Folder,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
Contacts,Folder,Folder,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
D,Folder,Folder,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
D\Apps,Folder,Folder,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
D\Apps\HomeAssistant,Folder,Folder,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT